name: Build and deploy PHP app to Azure Web App - laravel-app-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Validate composer.json and install dependencies
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          composer validate --no-check-publish
          if ! composer install --dry-run --no-scripts; then
            echo "The composer.lock file is not up to date with composer.json."
            echo "Running composer update to synchronize lock file."
            composer update --no-progress
            echo "Remember to commit the updated composer.lock file to your repository."
          else
            composer install --prefer-dist --no-progress

      - name: Zip artifact for deployment
        run: zip -r release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'laravel-app-server'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_705B89010DD245658D368C49B9E8ECC1 }}
